from . import sale_order
from . import res_partner
from . import sale_order_line
from . import account_move
from . import stock_picking
from . import stock_move
from . import product_template
from . import purchase_order
from . import stock_rule
